//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Covoiturage
    {
        public Covoiturage()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int id_covoiturage { get; set; }
        public Nullable<int> id_chauffeur { get; set; }
        public string depart { get; set; }
        public string arrive { get; set; }
        public Nullable<System.DateTime> date_depart { get; set; }
        public Nullable<int> tarif { get; set; }
        public Nullable<System.DateTime> dateCreation { get; set; }
        public Nullable<int> nb_place { get; set; }
        public Nullable<bool> is_full { get; set; }
    
        public virtual ICollection<Reservation> Reservation { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
