//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int id_reservation { get; set; }
        public Nullable<int> id_covoiturage { get; set; }
        public Nullable<int> id_utilisateur { get; set; }
        public Nullable<bool> is_validate { get; set; }
    
        public virtual Covoiturage Covoiturage { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
