//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicule
    {
        public Vehicule()
        {
            this.Assoc_Utilisateur_vehicule = new HashSet<Assoc_Utilisateur_vehicule>();
        }
    
        public int id_vehicule { get; set; }
        public string marque { get; set; }
        public string model { get; set; }
    
        public virtual ICollection<Assoc_Utilisateur_vehicule> Assoc_Utilisateur_vehicule { get; set; }
    }
}
