//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoiteAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boite_Livre
    {
        public int id_boite_livre { get; set; }
        public Nullable<int> id_boite { get; set; }
        public Nullable<int> id_livre { get; set; }
    
        public virtual Boite Boite { get; set; }
        public virtual Livre Livre { get; set; }
    }
}
